using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Text;
using System.Text.RegularExpressions;


public class BinaryCode
{
	public string[] decode(string message)
	{
        return new string[] { "test" };
	}

    // BEGIN KAWIGIEDIT TESTING
    // Generated by KawigiEdit 2.1.4 (beta) modified by pivanof
    #region Testing code generated by KawigiEdit
    [STAThread]
    private static Boolean KawigiEdit_RunTest(int testNum, string p0, Boolean hasAnswer, string[] p1)
    {
        Console.Write("Test " + testNum + ": [" + "\"" + p0 + "\"");
        Console.WriteLine("]");
        BinaryCode obj;
        string[] answer;
        obj = new BinaryCode();
        DateTime startTime = DateTime.Now;
        answer = obj.decode(p0);
        DateTime endTime = DateTime.Now;
        Boolean res;
        res = true;
        Console.WriteLine("Time: " + (endTime - startTime).TotalSeconds + " seconds");
        if (hasAnswer)
        {
            Console.WriteLine("Desired answer:");
            Console.Write("\t" + "{");
            for (int i = 0; p1.Length > i; ++i)
            {
                if (i > 0)
                {
                    Console.Write(",");
                }
                Console.Write("\"" + p1[i] + "\"");
            }
            Console.WriteLine("}");
        }
        Console.WriteLine("Your answer:");
        Console.Write("\t" + "{");
        for (int i = 0; answer.Length > i; ++i)
        {
            if (i > 0)
            {
                Console.Write(",");
            }
            Console.Write("\"" + answer[i] + "\"");
        }
        Console.WriteLine("}");
        if (hasAnswer)
        {
            if (answer.Length != p1.Length)
            {
                res = false;
            }
            else
            {
                for (int i = 0; answer.Length > i; ++i)
                {
                    if (answer[i] != p1[i])
                    {
                        res = false;
                    }
                }
            }
        }
        if (!res)
        {
            Console.WriteLine("DOESN'T MATCH!!!!");
        }
        else if ((endTime - startTime).TotalSeconds >= 2)
        {
            Console.WriteLine("FAIL the timeout");
            res = false;
        }
        else if (hasAnswer)
        {
            Console.WriteLine("Match :-)");
        }
        else
        {
            Console.WriteLine("OK, but is it right?");
        }
        Console.WriteLine("");
        return res;
    }
    public static void Main(string[] args)
    {
        Boolean all_right;
        all_right = true;

        string p0;
        string[] p1;

        // ----- test 0 -----
        p0 = "123210122";
        p1 = new string[] { "011100011", "NONE" };
        all_right = KawigiEdit_RunTest(0, p0, true, p1) && all_right;
        // ------------------

        // ----- test 1 -----
        p0 = "11";
        p1 = new string[] { "01", "10" };
        all_right = KawigiEdit_RunTest(1, p0, true, p1) && all_right;
        // ------------------

        // ----- test 2 -----
        p0 = "22111";
        p1 = new string[] { "NONE", "11001" };
        all_right = KawigiEdit_RunTest(2, p0, true, p1) && all_right;
        // ------------------

        // ----- test 3 -----
        p0 = "123210120";
        p1 = new string[] { "NONE", "NONE" };
        all_right = KawigiEdit_RunTest(3, p0, true, p1) && all_right;
        // ------------------

        // ----- test 4 -----
        p0 = "3";
        p1 = new string[] { "NONE", "NONE" };
        all_right = KawigiEdit_RunTest(4, p0, true, p1) && all_right;
        // ------------------

        // ----- test 5 -----
        p0 = "12221112222221112221111111112221111";
        p1 = new string[] { "01101001101101001101001001001101001", "10110010110110010110010010010110010" };
        all_right = KawigiEdit_RunTest(5, p0, true, p1) && all_right;
        // ------------------

        if (all_right)
        {
            Console.WriteLine("You're a stud (at least on the example cases)!");
        }
        else
        {
            Console.WriteLine("Some of the test cases had errors.");
        }
    }
    #endregion
    // END KAWIGIEDIT TESTING
}
//Powered by KawigiEdit 2.1.4 (beta) modified by pivanof!

